CREATE TABLE sr_dag_execution_report_audit (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_type VARCHAR(16) NOT NULL,
    accepted    BOOLEAN NOT NULL,
    reason      VARCHAR(128),
    report_json JSONB NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_sr_dag_execution_report_audit_created
    ON sr_dag_execution_report_audit(created_at, id);
