-- =============================================================================
-- V5: DAG 编排骨架
--
-- 引入 DAG 定义、DAG 定义版本、DAG 实例、节点实例、边、产物表。
-- 节点实例状态机对齐 DAG_Engine_Scheduler_Executor_设计总结.md：
--   - DagInstance: INIT/RUNNING/SUCCESS/FAILED/CANCELLED（间隔编码 0/10/20/30/40）
--   - NodeInstance: WAITING/READY/DISPATCHING/DISPATCHED/RUNNING/SUCCESS/FAILED/CANCELLED/SKIPPED/TIMEOUT
--   - 去掉 orchestration_state 子状态机
--   - 创建时统一初始化为 WAITING / INIT，由 DAG Engine 首轮 CAS 推进根节点
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. DAG 定义（元信息）
-- -----------------------------------------------------------------------------
CREATE TABLE sr_dag_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id          BIGINT       NOT NULL,
    dag_code        VARCHAR(128) NOT NULL,
    dag_name        VARCHAR(256) NOT NULL,
    description     VARCHAR(1000),
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_sr_dag_definition_code UNIQUE (app_id, dag_code)
);

COMMENT ON TABLE  sr_dag_definition IS 'DAG 定义元信息';
COMMENT ON COLUMN sr_dag_definition.app_id IS '所属应用，关联 sr_application';
COMMENT ON COLUMN sr_dag_definition.dag_code IS '业务编码，例如 qldksc-workflow';

-- -----------------------------------------------------------------------------
-- 2. DAG 定义版本（不可变，发布时强制拓扑校验）
-- -----------------------------------------------------------------------------
CREATE TABLE sr_dag_definition_version (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dag_definition_id     BIGINT       NOT NULL,
    version_no            INTEGER      NOT NULL,
    status                INTEGER      NOT NULL DEFAULT 0,
    definition_snapshot   JSONB        NOT NULL,
    definition_hash       VARCHAR(64)  NOT NULL,
    published_at          TIMESTAMPTZ,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_sr_dag_version_definition
        FOREIGN KEY (dag_definition_id) REFERENCES sr_dag_definition(id),
    CONSTRAINT uk_sr_dag_version UNIQUE (dag_definition_id, version_no),
    -- status: 0=DRAFT, 10=ENABLED, 20=DISABLED
    CONSTRAINT ck_sr_dag_version_status CHECK (status IN (0, 10, 20))
);

CREATE UNIQUE INDEX uk_sr_dag_version_hash ON sr_dag_definition_version (definition_hash);

COMMENT ON TABLE  sr_dag_definition_version IS 'DAG 定义版本，发布后不可变';
COMMENT ON COLUMN sr_dag_definition_version.definition_snapshot IS '完整 DAG JSON（nodes + edges + inputs）';
COMMENT ON COLUMN sr_dag_definition_version.definition_hash IS 'SHA-256(definition_snapshot)，用于一致性校验';
COMMENT ON COLUMN sr_dag_definition_version.status IS '0=DRAFT, 10=ENABLED（通过拓扑校验后发布）, 20=DISABLED';

-- -----------------------------------------------------------------------------
-- 3. DAG 边定义（含控制依赖 + 数据依赖推导出的隐式边）
-- -----------------------------------------------------------------------------
CREATE TABLE sr_dag_edge (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dag_definition_version_id   BIGINT       NOT NULL,
    from_node_id                VARCHAR(128) NOT NULL,
    to_node_id                  VARCHAR(128) NOT NULL,
    edge_type                   INTEGER      NOT NULL,
    condition_expr              VARCHAR(500),
    created_at                  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_sr_dag_edge_version
        FOREIGN KEY (dag_definition_version_id) REFERENCES sr_dag_definition_version(id),
    CONSTRAINT uk_sr_dag_edge UNIQUE (dag_definition_version_id, from_node_id, to_node_id, edge_type),
    -- edge_type: 0=CONTROL, 1=DATA
    CONSTRAINT ck_sr_dag_edge_type CHECK (edge_type IN (0, 1))
);

CREATE INDEX idx_sr_dag_edge_successor ON sr_dag_edge (dag_definition_version_id, from_node_id);
CREATE INDEX idx_sr_dag_edge_predecessor ON sr_dag_edge (dag_definition_version_id, to_node_id);

COMMENT ON COLUMN sr_dag_edge.edge_type IS 'CONTROL=显式控制依赖，DATA=由 input binding ${nodes.X.outputs.Y} 推导的隐式边';

-- -----------------------------------------------------------------------------
-- 4. DAG 实例（去掉 orchestration_state，状态机对齐文档）
-- -----------------------------------------------------------------------------
CREATE TABLE sr_dag_instance (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dag_definition_version_id   BIGINT       NOT NULL,
    dag_code_snapshot           VARCHAR(128) NOT NULL,
    dag_version_snapshot        INTEGER      NOT NULL,
    definition_hash_snapshot    VARCHAR(64)  NOT NULL,

    business_id                 VARCHAR(128),
    idempotency_key             VARCHAR(128) NOT NULL,
    input_json                  JSONB        NOT NULL DEFAULT '{}'::JSONB,

    -- status: 0=INIT, 10=RUNNING, 20=SUCCESS, 30=FAILED, 40=CANCELLED
    status                      INTEGER      NOT NULL DEFAULT 0,

    -- DAG 实例级租约（多实例 DAG Engine 抢占用）
    worker_id                   VARCHAR(160),
    lease_version               BIGINT       NOT NULL DEFAULT 0,
    heartbeat_time              TIMESTAMPTZ,
    lease_expire_time           TIMESTAMPTZ,
    last_progress_time          TIMESTAMPTZ,

    total_node_count            INTEGER      NOT NULL DEFAULT 0,
    success_node_count          INTEGER      NOT NULL DEFAULT 0,
    failed_node_count           INTEGER      NOT NULL DEFAULT 0,
    skipped_node_count          INTEGER      NOT NULL DEFAULT 0,

    next_schedule_time          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    started_at                  TIMESTAMPTZ,
    finished_at                 TIMESTAMPTZ,
    error_code                  VARCHAR(64),
    error_message               TEXT,

    created_at                   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at                   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT uk_sr_dag_instance_idempotency UNIQUE (idempotency_key),
    CONSTRAINT fk_sr_dag_instance_version
        FOREIGN KEY (dag_definition_version_id) REFERENCES sr_dag_definition_version(id),
    -- status: 0=INIT, 10=RUNNING, 20=SUCCESS, 30=FAILED, 40=CANCELLED
    CONSTRAINT ck_sr_dag_instance_status CHECK (status IN (0, 10, 20, 30, 40))
);

-- 扫描 INIT 实例（NodeInstance 创建完后 CAS 到 RUNNING）
CREATE INDEX idx_sr_dag_instance_init
    ON sr_dag_instance (next_schedule_time, id)
    WHERE status = 0;

-- 扫描 RUNNING 实例（DAG Engine 轮询推进）
CREATE INDEX idx_sr_dag_instance_running
    ON sr_dag_instance (last_progress_time, id)
    WHERE status = 10;

-- 租约过期扫描
CREATE INDEX idx_sr_dag_instance_lease
    ON sr_dag_instance (lease_expire_time, id)
    WHERE status = 10;

COMMENT ON TABLE  sr_dag_instance IS 'DAG 实例';
COMMENT ON COLUMN sr_dag_instance.status IS '0=INIT, 10=RUNNING, 20=SUCCESS, 30=FAILED, 40=CANCELLED';
COMMENT ON COLUMN sr_dag_instance.lease_version IS 'DAG 实例级租约版本，多实例 DAG Engine 抢占用';
COMMENT ON COLUMN sr_dag_instance.last_progress_time IS '最后一次节点状态推进时间，用于卡住检测';

-- -----------------------------------------------------------------------------
-- 5. DAG 节点实例（原 sr_dag_node_execution 重命名，去掉 orchestration_state）
-- -----------------------------------------------------------------------------
CREATE TABLE sr_dag_node_instance (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dag_instance_id             BIGINT       NOT NULL,
    node_id                     VARCHAR(128) NOT NULL,
    node_name_snapshot          VARCHAR(256),
    handler_name_snapshot       VARCHAR(128) NOT NULL,

    -- status: 0=WAITING, 10=READY, 20=DISPATCHING, 30=DISPATCHED, 40=RUNNING,
    --         50=SUCCESS, 60=FAILED, 70=CANCELLED, 80=SKIPPED, 90=TIMEOUT
    status                      INTEGER      NOT NULL DEFAULT 0,

    -- 重试与调度控制
    retry_count                 INTEGER      NOT NULL DEFAULT 0,
    current_attempt_no          INTEGER      NOT NULL DEFAULT 0,
    next_schedule_time          TIMESTAMPTZ,
    dispatch_owner              VARCHAR(160),
    dispatch_lease_expire_time  TIMESTAMPTZ,

    -- 节点级 CAS 乐观锁
    version                     BIGINT       NOT NULL DEFAULT 0,

    -- 输入绑定快照（WAITING→READY 时冻结）
    input_bindings_snapshot     JSONB        NOT NULL DEFAULT '{}'::JSONB,

    -- 结果
    result_json                 JSONB,
    result_ref                  VARCHAR(1000),
    error_code                  VARCHAR(64),
    error_message               TEXT,
    waiting_reason              VARCHAR(64),

    ready_at                    TIMESTAMPTZ,
    dispatched_at               TIMESTAMPTZ,
    started_at                  TIMESTAMPTZ,
    finished_at                 TIMESTAMPTZ,
    created_at                  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT uk_sr_dag_node_instance UNIQUE (dag_instance_id, node_id),
    CONSTRAINT fk_sr_dag_node_instance_dag
        FOREIGN KEY (dag_instance_id) REFERENCES sr_dag_instance(id),
    -- status: 0=WAITING, 10=READY, 20=DISPATCHING, 30=DISPATCHED, 40=RUNNING,
    --         50=SUCCESS, 60=FAILED, 70=CANCELLED, 80=SKIPPED, 90=TIMEOUT
    CONSTRAINT ck_sr_dag_node_status CHECK (status IN (0, 10, 20, 30, 40, 50, 60, 70, 80, 90))
);

-- 扫描 WAITING 节点（DAG Engine 推进根节点 / 后继节点）
CREATE INDEX idx_sr_dag_node_waiting
    ON sr_dag_node_instance (dag_instance_id, node_id)
    WHERE status = 0;

-- 扫描 READY 节点（Scheduler 领取）
CREATE INDEX idx_sr_dag_node_ready
    ON sr_dag_node_instance (dag_instance_id)
    WHERE status = 10;

-- 扫描 DISPATCHING 卡住节点（回退扫描）
CREATE INDEX idx_sr_dag_node_dispatching
    ON sr_dag_node_instance (dispatch_lease_expire_time)
    WHERE status = 20;

-- 扫描 RUNNING 节点（卡住检测）
CREATE INDEX idx_sr_dag_node_running
    ON sr_dag_node_instance (dag_instance_id)
    WHERE status = 40;

COMMENT ON TABLE  sr_dag_node_instance IS 'DAG 节点实例，创建时统一初始化为 WAITING';
COMMENT ON COLUMN sr_dag_node_instance.status IS
    '0=WAITING, 10=READY, 20=DISPATCHING, 30=DISPATCHED, 40=RUNNING, 50=SUCCESS, 60=FAILED, 70=CANCELLED, 80=SKIPPED, 90=TIMEOUT';
COMMENT ON COLUMN sr_dag_node_instance.retry_count IS '已重试次数（不含首次）';
COMMENT ON COLUMN sr_dag_node_instance.current_attempt_no IS '当前 Attempt 编号，从 1 递增';
COMMENT ON COLUMN sr_dag_node_instance.input_bindings_snapshot IS 'WAITING→READY 时解析并冻结的输入绑定';
COMMENT ON COLUMN sr_dag_node_instance.waiting_reason IS 'NO_EXECUTOR_AVAILABLE / BINDING_INVALID';
COMMENT ON COLUMN sr_dag_node_instance.result_ref IS '外部存储引用（文件/对象存储 URI），与 result_json 互补';

-- -----------------------------------------------------------------------------
-- 6. DAG Artifact（节点产物引用）
-- -----------------------------------------------------------------------------
CREATE TABLE sr_dag_artifact (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dag_instance_id         BIGINT       NOT NULL,
    node_id                 VARCHAR(128) NOT NULL,
    output_name             VARCHAR(128) NOT NULL,

    artifact_type           INTEGER      NOT NULL,
    storage_type            VARCHAR(32),
    uri                     TEXT,
    value_json              JSONB,
    metadata                JSONB,

    parent_artifact_ids     BIGINT[],

    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT uk_sr_dag_artifact UNIQUE (dag_instance_id, node_id, output_name),
    CONSTRAINT fk_sr_dag_artifact_dag_instance
        FOREIGN KEY (dag_instance_id) REFERENCES sr_dag_instance(id),
    -- artifact_type: 0=INLINE, 1=FILE, 2=DATABASE, 3=OBJECT_STORAGE
    CONSTRAINT ck_sr_dag_artifact_type CHECK (artifact_type IN (0, 1, 2, 3))
);

CREATE INDEX idx_sr_dag_artifact_ref ON sr_dag_artifact (dag_instance_id, node_id);

COMMENT ON TABLE  sr_dag_artifact IS 'DAG 节点产物引用，实际数据走业务侧存储';
COMMENT ON COLUMN sr_dag_artifact.artifact_type IS 'INLINE/FILE/DATABASE/OBJECT_STORAGE';
COMMENT ON COLUMN sr_dag_artifact.parent_artifact_ids IS '数据血缘，引用上游 Artifact ID';
