-- =============================================================================
-- V6: Handler 定义表
--
-- 原有 fanout_strategy 字段已移至 V7（在 sr_dag_node_instance 上添加）。
-- Handler 定义表保留用于发布期静态校验 dag_node.handler 引用是否存在。
-- 后续可由 AlgorithmDefinition 替代，当前保留兼容。
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Handler 定义表（描述"怎么执行"）
-- -----------------------------------------------------------------------------
CREATE TABLE sr_handler_definition (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id                  BIGINT       NOT NULL,
    handler_name            VARCHAR(128) NOT NULL,
    handler_version         INTEGER      NOT NULL DEFAULT 1,
    implementation_class    VARCHAR(512) NOT NULL,
    description             VARCHAR(1000),
    parameter_schema        JSONB,
    result_schema           JSONB,
    runtime_requirements    JSONB,
    timeout_seconds         INTEGER,
    is_active               BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_sr_handler_definition UNIQUE (app_id, handler_name, handler_version)
);

COMMENT ON TABLE  sr_handler_definition IS 'Handler 定义元信息，描述"怎么执行"';
COMMENT ON COLUMN sr_handler_definition.handler_name IS '业务 handler 名，对齐 @DistributedTask.value';
COMMENT ON COLUMN sr_handler_definition.implementation_class IS '实现类全限定名，便于反查与文档化';
COMMENT ON COLUMN sr_handler_definition.parameter_schema IS '入参 JSON Schema，发布期校验 dag_node.inputs';
COMMENT ON COLUMN sr_handler_definition.result_schema IS '出参 JSON Schema，校验 handler 返回值';
COMMENT ON COLUMN sr_handler_definition.runtime_requirements IS '运行时需求，如 {"cpu":"2","memory":"1G","gpu":1}';
COMMENT ON COLUMN sr_handler_definition.timeout_seconds IS 'handler 默认超时，可被 dag_node.timeout_seconds 覆盖';
