-- =============================================================================
-- V7: DAG 调度与执行层
--
-- 新增三张表，对齐 DAG_Engine_Scheduler_Executor_设计总结.md：
--   1. sr_dag_node_attempt：节点每次真实执行尝试
--   2. sr_algorithm_definition：可调度算法能力（executorGroup + 超时 + 重试策略）
--   3. sr_executor_registration：Worker 注册信息（存活 + 能力声明）
--
-- 同时为 sr_dag_node_instance 增加 fanout_strategy 字段。
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. sr_dag_node_instance 增加 fanout_strategy
-- -----------------------------------------------------------------------------
ALTER TABLE sr_dag_node_instance
    ADD COLUMN fanout_strategy INTEGER NOT NULL DEFAULT 0;

-- fanout_strategy: 0=SINGLE, 1=SHARD, 2=REPLICATE
ALTER TABLE sr_dag_node_instance
    ADD CONSTRAINT ck_sr_dag_node_fanout
        CHECK (fanout_strategy IN (0, 1, 2));

COMMENT ON COLUMN sr_dag_node_instance.fanout_strategy IS
    '节点扇出策略：0=SINGLE（1:1 NodeAttempt，阶段一），1=SHARD/2=REPLICATE=节点内分片并行（阶段三预留）';

-- -----------------------------------------------------------------------------
-- 2. DAG 节点执行尝试（每次真实执行产生一条）
-- -----------------------------------------------------------------------------
CREATE TABLE sr_dag_node_attempt (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dag_instance_id         BIGINT       NOT NULL,
    node_instance_id        BIGINT       NOT NULL,
    attempt_no              INTEGER      NOT NULL,
    request_id              VARCHAR(128) NOT NULL,

    algorithm_code          VARCHAR(128) NOT NULL,
    worker_id               VARCHAR(160),
    worker_address          VARCHAR(512),

    -- status: 0=CREATED, 10=DISPATCHING, 20=ACCEPTED, 30=RUNNING,
    --         40=SUCCESS, 50=FAILED, 60=CANCELLED, 70=TIMEOUT, 80=UNKNOWN
    status                  INTEGER      NOT NULL DEFAULT 0,

    request_json            JSONB,
    result_json             JSONB,
    result_ref               VARCHAR(1000),
    error_code              VARCHAR(64),
    error_message           TEXT,

    version                 BIGINT       NOT NULL DEFAULT 0,

    dispatched_at           TIMESTAMPTZ,
    accepted_at            TIMESTAMPTZ,
    started_at             TIMESTAMPTZ,
    finished_at             TIMESTAMPTZ,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT uk_sr_dag_node_attempt UNIQUE (node_instance_id, attempt_no),
    CONSTRAINT uk_sr_dag_node_attempt_request UNIQUE (request_id),
    CONSTRAINT fk_sr_dag_node_attempt_instance
        FOREIGN KEY (node_instance_id) REFERENCES sr_dag_node_instance(id),
    CONSTRAINT fk_sr_dag_node_attempt_dag
        FOREIGN KEY (dag_instance_id) REFERENCES sr_dag_instance(id),
    -- status: 0=CREATED, 10=DISPATCHING, 20=ACCEPTED, 30=RUNNING,
    --         40=SUCCESS, 50=FAILED, 60=CANCELLED, 70=TIMEOUT, 80=UNKNOWN
    CONSTRAINT ck_sr_dag_node_attempt_status CHECK (status IN (0, 10, 20, 30, 40, 50, 60, 70, 80))
);

-- 扫描 RUNNING Attempt（Scheduler 超时检测）
CREATE INDEX idx_sr_dag_node_attempt_running
    ON sr_dag_node_attempt (started_at, id)
    WHERE status = 30;

-- 扫描终态但未处理的 Attempt（DAG Engine 推进 NodeInstance）
CREATE INDEX idx_sr_dag_node_attempt_terminal
    ON sr_dag_node_attempt (node_instance_id, id)
    WHERE status IN (40, 50, 70, 80);

COMMENT ON TABLE  sr_dag_node_attempt IS 'DAG 节点每次真实执行尝试';
COMMENT ON COLUMN sr_dag_node_attempt.status IS
    '0=CREATED, 10=DISPATCHING, 20=ACCEPTED, 30=RUNNING, 40=SUCCESS, 50=FAILED, 60=CANCELLED, 70=TIMEOUT, 80=UNKNOWN';
COMMENT ON COLUMN sr_dag_node_attempt.request_id IS '远程调用幂等键，Worker 侧用此去重';
COMMENT ON COLUMN sr_dag_node_attempt.result_ref IS '外部存储引用，与 result_json 互补';

-- -----------------------------------------------------------------------------
-- 3. 算法定义（可调度算法能力）
-- -----------------------------------------------------------------------------
CREATE TABLE sr_algorithm_definition (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    algorithm_code              VARCHAR(128) NOT NULL,
    algorithm_name              VARCHAR(256) NOT NULL,
    executor_group_code         VARCHAR(128) NOT NULL,
    invoke_mode                 VARCHAR(32)  NOT NULL DEFAULT 'SYNC',
    timeout_seconds             INTEGER      NOT NULL DEFAULT 300,
    max_retry                   INTEGER      NOT NULL DEFAULT 0,
    retry_interval_seconds      INTEGER      NOT NULL DEFAULT 10,
    input_schema_json           JSONB,
    output_schema_json          JSONB,
    -- status: 0=DISABLED, 10=ENABLED
    status                      INTEGER      NOT NULL DEFAULT 0,
    description                 VARCHAR(1000),
    created_at                  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_sr_algorithm_definition UNIQUE (algorithm_code)
);

COMMENT ON TABLE  sr_algorithm_definition IS '可调度算法能力，Scheduler 据此选择 executorGroup';
COMMENT ON COLUMN sr_algorithm_definition.algorithm_code IS '算法编码，如 DATA_PREPARE / INTERSECTION / RESULT_STAT';
COMMENT ON COLUMN sr_algorithm_definition.executor_group_code IS '执行组编码，如 GIS_EXECUTOR，对应 ExecutorRegistration';
COMMENT ON COLUMN sr_algorithm_definition.invoke_mode IS 'SYNC=同步等待结果, ASYNC=异步回调';
COMMENT ON COLUMN sr_algorithm_definition.timeout_seconds IS '单次执行超时，Scheduler 据此扫描超时 Attempt';
COMMENT ON COLUMN sr_algorithm_definition.max_retry IS '最大重试次数（不含首次）';
COMMENT ON COLUMN sr_algorithm_definition.status IS '0=DISABLED, 10=ENABLED';

-- -----------------------------------------------------------------------------
-- 4. Worker 注册信息（当前存活的 Executor）
-- -----------------------------------------------------------------------------
CREATE TABLE sr_executor_registration (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    executor_group_code        VARCHAR(128) NOT NULL,
    worker_id                   VARCHAR(160) NOT NULL,
    address                     VARCHAR(512) NOT NULL,
    capabilities_json           JSONB        NOT NULL DEFAULT '[]'::JSONB,
    -- status: 0=OFFLINE, 10=ONLINE, 20=DRAINING
    status                      INTEGER      NOT NULL DEFAULT 0,
    max_concurrency             INTEGER      NOT NULL DEFAULT 1,
    running_task_count          INTEGER      NOT NULL DEFAULT 0,
    weight                      INTEGER      NOT NULL DEFAULT 1,
    registered_at               TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    last_heartbeat_time         TIMESTAMPTZ,
    lease_expire_time           TIMESTAMPTZ,
    updated_at                  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_sr_executor_registration UNIQUE (executor_group_code, worker_id)
);

-- 扫描 ONLINE Worker（Scheduler 选择）
CREATE INDEX idx_sr_executor_online
    ON sr_executor_registration (executor_group_code)
    WHERE status = 10;

-- 扫描 lease 过期（Worker 宕机检测）
CREATE INDEX idx_sr_executor_lease
    ON sr_executor_registration (lease_expire_time)
    WHERE status = 10;

COMMENT ON TABLE  sr_executor_registration IS 'Worker 注册信息，表示当前哪些 Worker 存活';
COMMENT ON COLUMN sr_executor_registration.executor_group_code IS '执行组编码，与 AlgorithmDefinition 对应';
COMMENT ON COLUMN sr_executor_registration.capabilities_json IS '能力列表 JSON 数组，如 ["DATA_PREPARE","INTERSECTION"]';
COMMENT ON COLUMN sr_executor_registration.status IS '0=OFFLINE, 10=ONLINE, 20=DRAINING';
COMMENT ON COLUMN sr_executor_registration.lease_expire_time IS '租约过期时间，过期后不再派发任务';
